### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by aendrew** [ft-interactive/load-data#1]
- [ ] Set up CircleCI
- [ ] Set up automated NPM publishing
- [ ] Replace d3-dsv with [mholt/PapaParse](https://github.com/mholt/PapaParse); add config opts
- [ ] Add connection handling options (serial/parallel)
- [ ] XML parsing?
- [ ] NDJSON parsing?
- [ ] Markdown parsing?
- [ ] ArchieML parsing?
